export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_REQUST = 'FETCH_POSTS_REQUST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
